import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from './providers'; 
import Navbar from '../components/Navbar'; 
import { getServerSession } from 'next-auth/next'; 
import { authOptions } from './api/auth/[...nextauth]/route'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MediAppoint", 
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions); 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen w-full`}
      >
        <Providers>
          {session && <Navbar />}
          <main className="flex-grow w-full">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
